model:
  patch_size: 16
  tubelet_size: 1
  embed_dim: 768
  spatial_num_heads: 12
  spatial_num_layers: 12
  spatial_mlp_dim: 2048
  temporal_num_heads: 12
  temporal_num_layers: 12
  temporal_mlp_dim: 2048
  num_classes: 8
  max_seq_length: 17
  image_size: 224
  use_pretrained_encoder: vit
data:
  dataset_type: stream
  min_sequence_length: 2
  max_sequence_length: 16
  context_size: 8
  overlap: 2
  max_empty_frames: 3
  frame_sample_rate: 1
  num_channels: 3
  height: 224
  width: 224
  train_meta_file: /storage/plzen4-ntis/projects/korpusy_cv/RAVDAI/metadata/train_metadata.json
  val_meta_file: /storage/plzen4-ntis/projects/korpusy_cv/RAVDAI/metadata/val_metadata.json
  test_meta_file: /storage/plzen4-ntis/projects/korpusy_cv/RAVDAI/metadata/test_metadata.json
  train_json: /storage/plzen4-ntis/projects/korpusy_cv/RAVDAI/preloaded/balanced2_stream_train_data.json
  val_json: /storage/plzen4-ntis/projects/korpusy_cv/RAVDAI/preloaded/balanced2_stream_val_data.json
  test_json: /storage/plzen4-ntis/projects/korpusy_cv/RAVDAI/preloaded/balanced2_stream_test_data.json
  shuffle: true
  drop_last: true
  batch_size: 12
  num_workers: 8
  decord_num_threads: 8
  normalize: true
training:
  model_name: 0021-ViViT-B
  seed: 42
  learning_rate: 5.0e-05
  warmup_epochs: 0.5
  lr_scheduler: constant
  optimizer: adam
  loss: crossentropy
  epochs: 25
  log_step: 50
  eval_step: 2000
  save_step: 200
  checkpoint_save_dir: checkpoints
  load_from_checkpoint: None
  load_only_weights: false
  report_to: wandb
  balance_dataset: true
  gradient_accumulation_steps: 1
evaluation:
  checkpoint: checkpoints/model.pt
  dataset_meta_file: /storage/plzen4-ntis/projects/korpusy_cv/RAVDAI/annotations.json
